### ISSUE TITLE
Skill is not working from step 2.

### ISSUE THREAD

**Issue by vishaljsoni** [skills/continuous-integration#26] opened 2023-02-21 19:29 UTC
1. When I add a simple workflow, and add the code from step 1, my workflow never fails.
2. It shows all checks are passed, installs npm package and all. It never runs any tests.
3. I am not able to move to the next step.

![Screenshot 2023-02-21 at 1 28 56 PM](https://user-images.githubusercontent.com/16748299/220440430-6e7a4122-58a1-4633-b5eb-6983e35451c9.png)

**Comment by luispujols** [comment] 2023-02-22 18:51
Hey @vishaljsoni ! I just completed this skill and can confirm I was able to reproduce this same bug. 

**Root cause:** The linter is not catching any errors in the .md files of the repository because the error was recently moved to a different file in PR #25 from `README.md` to `resume.md` but given that the error was added at the top of the file and the file does not contain any other words with the emphasis syntax ("_") the error is not raised by the linter because the ` resume.md`  file markdown style is consistent. 

**Fix:** We need to move the error down in the file, and sprinkle 1 or more occurrences of emphasis using "_" instead of "*" in the resume.md file. (minimum 1 at the top of the file or in a line before the error)

I have created a PR #27 with the fix for this issue, once it's merged this step of the exercise should work as expected again.

cc: @heiskr would love your feedback here 🙌

**Closed** 2023-02-22 19:11 UTC
Labels: bug
